Proto/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from project import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Proto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name="index"),
    url(r'^project/$', views.index, name="index"),
    url(r'^project/log/$', views.indexlog, name="indexlog"),
    url(r'^project/players_text/$', views.players, name="players"),
    url(r'^project/players/$', views.players2, name="players2"),
    url(r'^project/playerslog/$', views.players2log, name="players2log"),
    url(r'^project/matchs/$', views.matchs, name="matchs"),
    url(r'^project/matchslog/$', views.matchslog, name="matchslog"),
    url(r'^project/api/players/$', views.players_json, name="players_json"),
    url(r'^project/player_details/(?P<player>\w+)/$', views.player_details, name="playerDetails"),
    url(r'^project/player_detailslog/(?P<player>\w+)/$', views.player_detailslog, name="playerDetailslog"),
    url(r'^project/api2/players/$', views.players_table, name="players_table"),
    url(r'^project/forms/$', views.new_account, name="new_account"),
    url(r'^project/team/$', views.team, name="team"),
    url(r'^project/teamlog/$', views.teamlog, name="teamlog"),
    url(r'^project/profil/$', views.profil, name="profil"),
    url(r'^project/forms_match/$',views.new_match, name="new_match"),
    #url(r'^project/addcomment/$', views.new_comment, name ="new_comment"),
    url(r'^project/matchmodif/(?P<match>\w+)/$', views.alter_match, name="alter_match"),


)

project/models.py
from django.db import models
from django import forms

# Match class
class Match(models.Model):
    place = models.CharField(max_length=200)
    date = models.DateField(auto_now=True)

    def loser(self):
        return self.participation_set.all().order_by("score")[0]

    def winer(self):
        return self.participation_set.all().order_by("score").reverse()[0]

    def __unicode__(self):
        return self.place

#Account class
class Account(models.Model):
    login = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    CHOICES=(('a','Admin'), ('a','Player'), ('g','Guest'))
    title = models.CharField(max_length=1, choices=CHOICES)

class Log(models.Model):
    login = models.CharField(max_length=200)

# Team class
class Team(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name


# Player class
class Player(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField(default=0)
    team = models.ForeignKey(Team, blank=True, on_delete=models.SET_NULL, null=True, default=None)

    def __unicode__(self):
        return self.name



# Participation Class
class Participation(models.Model):
    score = models.IntegerField(default=0)
    player = models.ForeignKey(Player)
    match = models.ForeignKey(Match)

    def __unicode__(self):
        return self.match.place + " " + self.player.name


# Participation Class
class ParticipationT(models.Model):
    score = models.IntegerField(default=0)
    team = models.ForeignKey(Team)
    match = models.ForeignKey(Match)

    def __unicode__(self):
        return self.match.place + " " + self.team.name

#Commentaire
class Comment(models.Model):
    comment = models.CharField(max_length=1000)
    match = models.ForeignKey(Match)

# new match class (Forms)
class newmatch(forms.Form):
    place = forms.CharField(label="Name", max_length=200, widget=forms.TextInput)
    date = forms.DateField(required = False)

    #liste = [ ,x.name for x in Player.objects.all()]
    #liste = (('a','a'))
    #choix = forms.MultipleChoiceField(label="Choices", widget=forms.CheckboxSelectMultiple, choices = Player.objects.all())
    player1 = forms.CharField(label="player1", max_length = 200, widget=forms.TextInput, required= True)
    player2 = forms.CharField(label="player2", max_length=200, widget=forms.TextInput, required = True)
    score1 = forms.IntegerField(label="score1")
    score2 = forms.IntegerField(label="score2")

class one_player(forms.Form):
    player = forms.ChoiceField(widget=forms.CheckboxInput, choices=('p',' '))


#new account class (Forms)
class newaccount(forms.Form):
    name = forms.CharField(label="login", max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Login'}))
    password = forms.CharField(label="password", max_length=200, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    age = forms.IntegerField(label="age")
    CHOICES=(('a','Admin'), ('a','Player'), ('g','Guest'))
    title = forms.ChoiceField(label="title", widget=forms.RadioSelect(), choices=CHOICES)
    team = forms.CharField(label="team", max_length=200, widget=forms.TextInput(attrs={'value': 'none'}))

class login(forms.Form):
    name = forms.CharField(label="login", max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Login'}))
    password = forms.CharField(label="password", max_length=200, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

class newcomment(forms.Form):
    name = forms.CharField(label="Name", max_length=200, widget = forms.TextInput)
    comment = forms.CharField(label="Comments", max_length=1000, widget = forms.TextInput)
    liste = []
    match = forms.ChoiceField(label = "Match", widget = forms.TextInput)

project/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from project.models import *
from django.core import serializers
import HTMLParser
import json

# Index page
def index(request):
      Log.objects.all().delete()
      if request.method == 'GET':
        form = login()
      else:
        form = login(request.POST)
        if form.is_valid() :
          name = form.cleaned_data["name"] #formate data recues
          password = form.cleaned_data["password"]

          for l in Account.objects.all():
            if l.login==name:
              if l.password==password:
                 personne=Log(login=name)
                 personne.save()
                 return HttpResponseRedirect(reverse('indexlog'))

      return render(request, "index.html", {"form": form})

#    return render(request, "index.html")


def indexlog(request):
    personne=Log.objects.all()[0]
    return render(request, "indexlog.html",{"personne": personne} )

# List all players in a simple way
def players(request):
    res = [x.name+"<br>" for x in Player.objects.all()]
    return HttpResponse(res, {"personne": personne})

# List all players in a simple way
def playerslog(request):
    res = [x.name+"<br>" for x in Player.objects.all()]
    return HttpResponse(res)


# List all players using templates
def players2(request):
    if request.method == 'GET':
      form = login()
    else:
      form = login(request.POST)
      if form.is_valid() :
        name = form.cleaned_data["name"] #formate data recues
        password = form.cleaned_data["password"]

        for l in Account.objects.all():
          if l.login==name:
            if l.password==password:
              personne=Log(login=name)
              personne.save()
              return HttpResponseRedirect(reverse('indexlog'))
    res = [x for x in Player.objects.all()]
    return render(request, "players.html", {"form": form, "players": res})

def players2log(request):
  personne=Log.objects.all()[0]
  res = [x for x in Player.objects.all()]
  return render(request, "playerslog.html", {"personne": personne, "players": res})

# List of Teams
def team(request):
    #account=Account.objects.all()
    #account.delete()
    if request.method == 'GET':
      form = login()
    else:
      form = login(request.POST)
      if form.is_valid() :
        name = form.cleaned_data["name"] #formate data recues
        password = form.cleaned_data["password"]

        for l in Account.objects.all():
          if l.login==name:
            if l.password==password:
              personne=Log(login=name)
              personne.save()
              return HttpResponseRedirect(reverse('indexlog'))
    res = [x for x in Team.objects.all()]
    people= []
    for x in range(Team.objects.count()):
      people.append(Player.objects.filter(team=Team.objects.all()[x]))
    return render(request, "team.html", {"form":form, "team": res, "people": people})

def teamlog(request):
  personne=Log.objects.all()[0]
  res = [x for x in Team.objects.all()]
  people = [x for x in Player.objects.all()]
  return render(request, "teamlog.html", {"personne":personne, "team": res, "people": people})


# List all matchs using templates
def matchs(request):
    if request.method == 'GET':
      form = login()
    else:
      form = login(request.POST)
      if form.is_valid() :
        name = form.cleaned_data["name"] #formate data recues
        password = form.cleaned_data["password"]

        for l in Account.objects.all():
          if l.login==name:
            if l.password==password:
              personne=Log(login=name)
              personne.save()
              return HttpResponseRedirect(reverse('indexlog'))

    res = [x for x in Match.objects.all()]
    return render(request, "matchs.html", {"form":form, "matchs": res})


def matchslog(request):
  personne=Log.objects.all()[0]
  res = [x for x in Match.objects.all()]
  return render(request, "matchslog.html", {"personne":personne, "matchs": res})

# List Player details
def player_details(request, player):
    if request.method == 'GET':
      form = login()
    else:
      form = login(request.POST)
      if form.is_valid() :
        name = form.cleaned_data["name"] #formate data recues
        password = form.cleaned_data["password"]

        for l in Account.objects.all():
          if l.login==name:
            if l.password==password:
              personne=Log(login=name)
              personne.save()
              return HttpResponseRedirect(reverse('indexlog'))
    res = next(x for x in Player.objects.all() if x.name == player)
    return render(request, "player_details.html", {"player": res, "form":form})

# List Player details
def player_detailslog(request, player):
    personne=Log.objects.all()[0]
    res = next(x for x in Player.objects.all() if x.name == player)
    return render(request, "player_detailslog.html", {"personne":personne, "player": res})


# List all players (JSON)
def players_json(request):
    res = []
    for p in Player.objects.all():
        c = len(Participation.objects.filter(player=p.id))
        res += [{ "name": p.name, "age": p.age, "matchesCount": c }]
    return HttpResponse(json.dumps(res), content_type="application/json")

def players_table(request):
    h = HTMLParser.HTMLParser()
    filter = h.unescape(request.GET.get('filter', ''))
    res = Player.objects.filter(name__icontains=filter)
    return render(request, "players_table.html", {"players": res})


# Liste des commentaires
def comments(request):
    personne=Log.objects.all()[0]
    res = [x for x in Comment.objects.all()]
    return render(request, "comments.html", {"personne":personne,"comments": res})


# Create new account
def new_account(request):
    if request.method == 'GET':
        res = newaccount()
    else:
        res = newaccount(request.POST)
        if res.is_valid() :
            name = res.cleaned_data["name"] #formate data recues
            age = res.cleaned_data["age"]
            password = res.cleaned_data["password"]
            title = res.cleaned_data["title"]
            team = res.cleaned_data["team"]
            appartien=False
            for n in Account.objects.all():
              if n.login==name:
                return HttpResponseRedirect(reverse('new_account'))
            for t in Team.objects.all():
              if t.name==team:
                appartien=True
                nt=t
            if appartien==False and team!="none":
              nt= Team(name=team)
              nt.save()
            if team=="none":
              nt=None
            if title!='g':
              p = Player(name=name, age=age, team=nt)
              p.save()
            l = Account(login=name, password=password, title=title)
            l.save()
            return HttpResponseRedirect(reverse('index'))

    return render(request, "new_account.html", {"res": res})

# Modify an account
def profil(request):
    personne=Log.objects.all()[0]
    if request.method == 'GET':
        res = newaccount()
    else:
        res = newaccount(request.POST)
        if res.is_valid() :
            name = res.cleaned_data["name"] #formate data recues
            age = res.cleaned_data["age"]
            password = res.cleaned_data["password"]
            title = res.cleaned_data["title"]
            team = res.cleaned_data["team"]
            appartien=False
            for t in Team.objects.all():
              if t.name==team:
                appartien=True
                nt=t
            if appartien==False and team!="none":
              nt= Team(name=team)
              nt.save()
            if team=="none":
              nt=None
            if title!='g':
              playermodif=Player.objects.filter(name=personne.login)
              playermodif.update(name=name, age=age, team=nt)
            accountmodif=Account.objects.filter(login=personne.login)
            accountmodif.update(login=name, password=password, title=title)
            Log.objects.filter(login=personne.login).update(login=name)
            return HttpResponseRedirect(reverse('indexlog'))

    return render(request, "profil.html", {"res": res, "personne": personne})

#Create a new match
def new_match(request):
    personne=Log.objects.all()[0]
    if request.method =='GET':
       res = newmatch()
    else:
        res = newmatch(request.POST)

        if res.is_valid():
            place = res.cleaned_data["place"]
            #date = res.cleaned_data["date"]
            player1 = res.cleaned_data['player1']
            player2 = res.cleaned_data['player2']
            score1 = res.cleaned_data['score1']
            score2 = res.cleaned_data['score2']
            m=Match(place = place)
            m.save()

            #loser=request.POST['loser']
            #winner = request.POST['winner']

            for p in Player.objects.all():
              if p.name==player1:
                Participation(player = p, match =m, score=score1).save()

            for p2 in Player.objects.all():
              if p2.name == player2:
                Participation(player = p2, match = m, score=score2).save()

            return HttpResponseRedirect(reverse('index'))
    return render(request, "new_match.html", {"res": res, "players": players,  "personne": personne})


# Modifier un match
def alter_match(request, name):
    personne=Log.objects.all()[0]
    if request.method =='GET':
       res = newmatch()
    else:
        res = newmatch(request.POST)

        if res.is_valid():
            place = res.cleaned_data["place"]
            #date = res.cleaned_data["date"]
            player1 = res.cleaned_data['player1']
            player2 = res.cleaned_data['player2']

            thematch = next(x for x in Match.objects.all() if x.place == name)

            match2 = Match.objects.filter(place = name)

            matchmodif = Match.objects.filter(place = name)

project/templates/alter_match.html
{% extends "indexlog.html" %}

{% block title %}Players list{% endblock %}

{% block head %}
{% load staticfiles %}
  <script src="{% static "js/filter-players.js" %}"></script>
{% endblock %}

{% block menu %}
 <li><a href="{% url 'index' %}">Home</a></li>
 <li><a href="{% url 'players2' %}">Players</a></li>
 <li><a href="{% url 'matchs' %}">Matchs</a></li>
{% endblock %}

{% block content %}
<form class="form-horizontal" role="form" action="/project/forms_match/" method="post">

{% csrf_token %}
<!-- Form Match -->
<legend>New match</legend>


    <div class="form-group">
      </br>


      {{ res.place}}

      </br>


      <input type="submit" onClick"submit" class="btn btn-success" value="Valider"/>
    </div>

</form>




{% endblock %}

project/templates/indexlog.html
<!DOCTYPE html>
<html lang="en">
  <head>
   {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Scores Simulator{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}" />

<!-- JQuery JavaScript -->
<script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js' %}"></script>


    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

  {% block head %}{% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project</a>
        </div>
        <div class="collapse navbar-collapse">

             <form class="navbar-form navbar-right">

            <div class="form-group">
              <a href="{% url 'profil' %}" id="profile" class="btn btn-info">{{personne.login}}</a>
            </div>
              <a href="{% url 'index' %}" class="btn btn-danger">Log out</a>
            <a href="{% url 'new_account' %}" class="btn btn-warning">New account</a>
          </form>
          <ul class="nav navbar-nav">
      {% block menu %}

         <li class="active"><a href="{% url 'indexlog' %}">Home</a></li>
         <li><a href="{% url 'players2log' %}">Players</a></li>
         <li><a href="{% url 'teamlog' %}">Teams</a></li>
         <li><a href="{% url 'matchslog' %}">Matchs</a></li>


      {% endblock %}
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
  <div class="contenu">
    {% block content %}
   <h1>Welcome to this Site</h1>
  <!-- images et autres -->
  {% endblock %}
   </div>
    </div>




    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

project/templates/matchs.html
{% extends "index.html" %}

{% block title %}Matchs list{% endblock %}

{% block menu %}
 <li><a href="{% url 'index' %}">Home</a></li>
 <li><a href="{% url 'players2' %}">Players</a></li>
 <li><a href="{% url 'team' %}">Teams</a></li>
 <li class="active"><a href="{% url 'matchs' %}">Matchs</a></li>
{% endblock %}


{% block content %}

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Matchs list</h3>
  </div>
  <div class="panel-body">
	<!-- Panel content -->
	<table class="table">
	 <thead>
	  <tr>
	    <th>Id</th>
	    <th>Name</th>
	    <th>Date</th>
	    <th>Winer</th>
	    <th>Loser</th>
	  </tr>
	 </thead>
	 <tbody>
	  {% for m in matchs  %}
	   <tr  id="{{m.id}}-par" onClick = "nomfunction('{{m.id}}')">
	    <td>{{m.id}}</td>
	    <td>{{m.place}}</td>
	    <td>{{m.date}}</td>
	    <td>{{m.winer.player.name}} <span class="badge">{{m.winer.score}}</span></td>
	    <td>{{m.loser.player.name}} <span class="badge">{{m.loser.score}}</span></td>
      <td><a href="{% url 'alter_match' m.place  %}">Modifier</a></td>
	  </tr >
    <tr>
      <p class="hello" id="{{m.id}}-comment" >
         Comments :
      </p>
    </tr>
	  {% endfor %}
    {% load static from staticfiles %}
<script type="text/javascript" src="{% static 'js/matchjs.js' %}"></script>

	 </tbody>
	</table>
   </div>
</div>

{% endblock %}

project/templates/matchslog.html
{% extends "indexlog.html" %}

{% block title %}Matchs list{% endblock %}

{% block menu %}
 <li><a href="{% url 'indexlog' %}">Home</a></li>
 <li><a href="{% url 'players2log' %}">Players</a></li>
 <li><a href="{% url 'teamlog' %}">Teams</a></li>
 <li class="active"><a href="{% url 'matchslog' %}">Matchs</a></li>
{% endblock %}


{% block content %}

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Matchs list</h3>
  </div>
  <div class="panel-body">
  <!-- Panel content -->
  <table class="table">
   <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Date</th>
      <th>Winer</th>
      <th>Loser</th>
      <th>Modifier</th>
    </tr>
   </thead>
   <tbody>
      <a href="{% url 'new_match' %}" class="btn btn-success">Add a new match</a>
    </br>
    </br>
    {% for m in matchs  %}
    	  <tr  id="{{m.id}}-par" onClick = "nomfunction('{{m.id}}')">
	    <td>{{m.id}}</td>
	    <td>{{m.place}}</td>
	    <td>{{m.date}}</td>
	    <td>{{m.winer.player.name}} <span class="badge">{{m.winer.score}}</span></td>
	    <td>{{m.loser.player.name}} <span class="badge">{{m.loser.score}}</span></td>
      <td><a href="{% url 'alter_match' m.place  %}">Modifier</a></td>
	  </tr >
    <tr >
      <p class="hello" id="{{m.id}}-comment" >
         Comments :
         <button class="add_comment">Ajouter un commentaire</button>
      </p>
    </tr>
	  {% endfor %}
{% load static from staticfiles %}
<script type="text/javascript" src="{% static 'js/matchjs.js' %}"></script>

	 </tbody>
	</table>
  </tr>
   </div>
</div>

{% endblock %}

project/templates/new_account.html
{% extends "index.html" %}

{% block title %}Players list{% endblock %}

{% block head %}
{% load staticfiles %}
  <script src="{% static "js/filter-players.js" %}"></script>
{% endblock %}

{% block menu %}
 <li><a href="{% url 'index' %}">Home</a></li>
 <li><a href="{% url 'players2' %}">Players</a></li>
 <li><a href="{% url 'matchs' %}">Matchs</a></li>
{% endblock %}

{% block content %}
<form class="form-horizontal" role="form" action="/project/forms/" method="post">

{% csrf_token %}
<!-- Form Name -->
<legend>New account</legend>


    <div class="form-group">
      </br>
      {{ res.as_ul }}
      </br>
      <input type="submit" onClick"submit" class="btn btn-success" value="Valider"/>
    </div>

</form>




{% endblock %}

project/templates/new_match.html
{% extends "indexlog.html" %}

{% block title %}Players list{% endblock %}

{% block head %}
{% load staticfiles %}
  <script src="{% static "js/filter-players.js" %}"></script>
{% endblock %}

{% block menu %}
 <li><a href="{% url 'index' %}">Home</a></li>
 <li><a href="{% url 'players2' %}">Players</a></li>
 <li><a href="{% url 'matchs' %}">Matchs</a></li>
{% endblock %}

{% block content %}
<form class="form-horizontal" role="form" action="/project/forms_match/" method="post">

{% csrf_token %}
<!-- Form Match -->
<legend>New match</legend>


    <div class="form-group">
      </br>


      {{ res.as_ul}}
    </br>

      <input type="submit" onClick"submit" class="btn btn-success" value="Valider"/>
    </div>

</form>




{% endblock %}

project/templates/player_details.html
{% extends "index.html" %}

{% block title %}Player {{ player.name }}{% endblock %}

{% block menu %}
 <li><a href="{% url 'index' %}">Home</a></li>
 <li class="active"><a href="{% url 'players2' %}">Players</a></li>
 <li><a href="{% url 'team' %}">Teams</a></li>
 <li><a href="{% url 'matchs' %}">Matchs</a></li>
{% endblock %}

{% block content %}

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Player: {{ player.name }}   &nbsp;&nbsp;&nbsp;  Age: {{ player.age }}  &nbsp;&nbsp;&nbsp;   Team: {{ player.team}}</h3>
  </div>
  <div class="panel-body">
	<!-- Panel content -->
	<table class="table">
	 <thead>
	  <tr>
	    <th>Place</th>
	    <th>Date</th>
	  </tr>
	 </thead>
	 <tbody>
   	  {% for p in player.participation_set.all %}
	  <tr>
	    <td>{{ p.match.place }}</td>
	    <td>{{ p.match.date }}</td>
	  </tr>
 	  {% endfor %}
	 </tbody>
	</table>
   </div>
</div>

{% endblock %}

project/templates/player_detailslog.html
{% extends "indexlog.html" %}

{% block title %}Player {{ player.name }}{% endblock %}

{% block menu %}
 <li><a href="{% url 'indexlog' %}">Home</a></li>
 <li class="active"><a href="{% url 'players2log' %}">Players</a></li>
 <li><a href="{% url 'teamlog' %}">Teams</a></li>
 <li><a href="{% url 'matchslog' %}">Matchs</a></li>
{% endblock %}

{% block content %}

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Player: {{ player.name }} &nbsp;&nbsp;&nbsp;  Age: {{ player.age }}  &nbsp;&nbsp;&nbsp;   Team: {{ player.team}}</h3>
  </div>
  <div class="panel-body">
  <!-- Panel content -->
  <table class="table">
   <thead>
    <tr>
      <th>Place</th>
      <th>Date</th>
    </tr>
   </thead>
   <tbody>
       {% for p in player.participation_set.all %}
    <tr>
      <td>{{ p.match.place }}</td>
      <td>{{ p.match.date }}</td>
    </tr>
     {% endfor %}
   </tbody>
  </table>
   </div>
</div>

{% endblock %}

project/templates/players_table.html
{% for p in players  %}
<tr>
  <td>{{p.name}}</td>
  <td>{{p.age}}</td>
  <!-- Generate dynamic link -->
  <td><a href="{% url 'playerDetails' p.name  %}">Matchs <span class="badge">{{ p.participation_set.count}}</span></a></td>
</tr>
{% endfor %}

project/templates/players_tablelog.html
{% for p in players  %}
<tr>
  <td>{{p.name}}</td>
  <td>{{p.age}}</td>
  <!-- Generate dynamic link -->
  <td><a href="{% url 'playerDetailslog' p.name  %}">Matchs <span class="badge">{{ p.participation_set.count}}</span></a></td>
</tr>
{% endfor %}

project/templates/team.html
{% extends "index.html" %}

{% block title %}Team list{% endblock %}

{% block head %}
{% load staticfiles %}
  <script src="{% static 'js/filter-players.js' %}"></script>
{% endblock %}

{% block menu %}
 <li><a href="{% url 'index' %}">Home</a></li>
 <li><a href="{% url 'players2' %}">Players</a></li>
 <li class="active"><a href="{% url 'team' %}">Team</a></li>
 <li><a href="{% url 'matchs' %}">Matchs</a></li>
{% endblock %}

{% block content %}
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Team list</h3>
  </div>
  <div class="panel-body">
    {% for t in team %}
    <table class="table">
     <thead>
      <tr>
        <th>{{t.name}}<span class="badge">{{ t.player_set.count}}</span></th>
      </tr>
     </thead>
     <tbody>
      {% for p in t.player_set.all %}
      <tr>
      <td> {{p.name}} </td>
      </tr>
      {% endfor %}
     </tbody>
       {% endfor %}
  </div>
</div>

{% endblock %}

project/templates/teamlog.html
{% extends "indexlog.html" %}

{% block title %}Team list{% endblock %}

{% block head %}
{% load staticfiles %}
  <script src="{% static 'js/filter-players.js' %}"></script>
{% endblock %}

{% block menu %}
 <li><a href="{% url 'indexlog' %}">Home</a></li>
 <li><a href="{% url 'players2log' %}">Players</a></li>
 <li class="active"><a href="{% url 'teamlog' %}">Team</a></li>
 <li><a href="{% url 'matchslog' %}">Matchs</a></li>
{% endblock %}

{% block content %}
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Team list</h3>
  </div>
  <div class="panel-body">
    {% for t in team %}
    <table class="table">
     <thead>
      <tr>
        <th>{{t.name}}<span class="badge">{{ t.player_set.count}}</span></th>
      </tr>
     </thead>
     <tbody>
      {% for p in t.player_set.all %}
      <tr>
      <td> {{p.name}} </td>
      </tr>
      {% endfor %}
     </tbody>
       {% endfor %}
  </div>
</div>

{% endblock %}